from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
urlpatterns = [
    path("login/", views.login_view, name="login"),
    path("logout/", auth_views.LogoutView.as_view(next_page='login'), name="logout"),
    path("api/verify-token/", views.api_verify_token, name="api_verify_token"),
    path("", views.home, name="home"),
    path("setup/", views.setup, name="setup"),
    path("complete_profile/", views.complete_profile, name="complete_profile"),
    path("check_match/", views.check_match, name="check_match"),
    path("api/quiz/batch/", views.get_quiz_batch, name="get_quiz_batch"),
    path("api/quiz/save/", views.save_quiz_batch, name="save_quiz_batch"),
    path("answer_question/<int:question_id>/", views.answer_question, name="answer_question"),
    path("match/send/<int:receiver_id>/", views.send_match_request, name="send_match_request"),
    path("match/skip/<int:receiver_id>/", views.skip_match, name="skip_match"),
    path("match/accept/<int:req_id>/", views.accept_match, name="accept_match"),
    path("match/reject/<int:req_id>/", views.reject_match, name="reject_match"),
    path("connections/", views.connections_view, name="connections"),
    path("chat/<int:partner_id>/", views.chat_view, name="chat_view"),
    path("chats/", views.chat_list_view, name="chat_list"),
    path("api/chat/<int:partner_id>/", views.chat_api_messages, name="chat_api_messages"),
    path("profile/edit/", views.edit_profile, name="edit_profile"),
    path("profile/<int:user_id>/", views.view_profile, name="view_profile"),
    path("profile/spark/<int:user_id>/", views.toggle_spark, name="toggle_spark"),
    path("profile/toggle-discoverable/", views.toggle_discoverable, name="toggle_discoverable"),
    path("profile/block/<int:user_id>/", views.block_user, name="block_user"),
    path("chat/delete/<int:partner_id>/", views.delete_chat, name="delete_chat"),
    path("announcements/", views.announcements_view, name="announcements"),
    path("profile/image/delete/<int:image_id>/", views.delete_profile_image, name="delete_profile_image"),
    path("run_migrations/", views.run_migrations, name="run_migrations"),
    path("wall/", views.wall_view, name="wall"),
    path("api/wall/", views.wall_api, name="wall_api"),
    path("confessions/", views.confessions_feed, name="confessions_feed"),
    path("confessions/create/", views.create_confession, name="create_confession"),
    path("confessions/<int:confession_id>/", views.confession_detail, name="confession_detail"),
    path("confessions/<int:confession_id>/edit/", views.edit_confession, name="edit_confession"),
    path("confessions/<int:confession_id>/delete/", views.delete_confession, name="delete_confession"),
    path("confessions/<int:confession_id>/report/", views.report_confession, name="report_confession"),
    path("report/user/<int:user_id>/", views.report_user, name="report_user"),
    path("confessions/<int:confession_id>/comment/", views.add_comment, name="add_comment"),
    path("confessions/<int:confession_id>/like/", views.like_confession, name="like_confession"),
    path("master/dashboard/", views.admin_dashboard, name="admin_dashboard"),
    path("master/action/", views.admin_action, name="admin_action"),
]