# Generated by Django 5.2.4 on 2025-08-01 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('age', models.PositiveIntegerField()),
                ('clg_year', models.IntegerField()),
                ('campus', models.CharField(blank=True, default='', max_length=100)),
                ('course', models.CharField(blank=True, default='', max_length=100)),
                ('branch', models.CharField(blank=True, default='', max_length=100)),
                ('living_place', models.CharField(blank=True, default='', max_length=100)),
                ('native_place', models.CharField(blank=True, default='', max_length=100)),
                ('languages', models.JSONField(default=list)),
                ('mother_tongues', models.JSONField(default=list)),
                ('bio', models.TextField(blank=True)),
                ('liked_songs', models.TextField(blank=True)),
                ('liked_movies', models.TextField(blank=True)),
                ('fav_shows', models.TextField(blank=True)),
                ('interest_tags', models.JSONField(default=list)),
                ('looking_for', models.CharField(choices=[('friendship', 'Friendship'), ('serious', 'Relationship'), ('vibe', 'Just vibing')], default='vibe', max_length=50)),
                ('pref_age_min', models.PositiveIntegerField(default=18)),
                ('pref_age_max', models.PositiveIntegerField(default=25)),
                ('pref_gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('any', 'Any')], default='any', max_length=10)),
                ('pref_languages', models.JSONField(default=list)),
                ('pref_campus', models.CharField(blank=True, max_length=100)),
                ('pref_branch', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
