# Generated by Django 5.2.4 on 2025-10-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_option_useranswer_delete_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='clg_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
