# Generated by Django 5.2.4 on 2026-03-28 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_profile_age_alter_profile_clg_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='weight',
            field=models.FloatField(default=0.0),
        ),
    ]
