# Generated by Django 5.2.4 on 2026-03-31 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_matchrequest_status_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='profileimage',
            name='image',
            field=models.URLField(max_length=500),
        ),
    ]
