# Generated by Django 5.2.4 on 2026-04-23 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_profile_profile_pic_alter_profileimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='interest_tags',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='languages',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mother_tongues',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pref_languages',
            field=models.TextField(blank=True, default=''),
        ),
    ]
