# Generated by Django 5.2.4 on 2026-04-23 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_profile_interest_tags_alter_profile_languages_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WallStroke',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.JSONField()),
                ('color', models.CharField(default='#ffffff', max_length=20)),
                ('brush_size', models.FloatField(default=2.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
