# Generated by Django 5.2.4 on 2026-04-23 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_confession_is_flagged_profile_is_banned_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='confessionreport',
            old_name='reason',
            new_name='other_reason',
        ),
        migrations.AddField(
            model_name='confessionreport',
            name='reasons',
            field=models.JSONField(default=list),
        ),
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reasons', models.JSONField(default=list)),
                ('other_reason', models.TextField(blank=True)),
                ('chat_snapshot', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reported_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_reports', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
