# Generated by Django 5.2.4 on 2026-04-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='receiver_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
