# Generated by Django 5.2.4 on 2026-04-23 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_message_reply_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_discoverable',
            field=models.BooleanField(default=False),
        ),
    ]
