# Generated by Django 5.2.4 on 2026-04-24 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_favoritemovie_favoritesong'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_face_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='verification_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
