# Generated by Django 5.2.4 on 2026-04-24 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_profile_is_face_verified_profile_verification_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='verification_image_left',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='verification_image_right',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('manual_review', 'Manual Review'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
