# Generated by Django 5.2.4 on 2026-04-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_userverification_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='userverification',
            name='face_match_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userverification',
            name='profile_photo_gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userverification',
            name='review_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
