# Generated by Django 5.2.4 on 2026-04-24 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_userverification_face_match_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_face_verified',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='verification_image',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='verification_image_left',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='verification_image_right',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='verification_status',
        ),
        migrations.DeleteModel(
            name='UserVerification',
        ),
    ]
