# Generated by Django 5.2.4 on 2026-04-24 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_remove_profile_is_face_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_face_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='verification_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('manual_review', 'Manual Review'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
