# Generated by Django 5.2.4 on 2026-04-25 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_profile_is_face_verified_profile_verification_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='pref_branch',
        ),
    ]
