# Generated by Django 5.2.4 on 2026-05-01 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_bannedidentifier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='confessioncomment',
            name='poster_fingerprint',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
