# Generated by Django 5.2.4 on 2026-05-04 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_confessioncomment_poster_fingerprint'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfessionRateLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(db_index=True, max_length=200)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['submitted_at'],
            },
        ),
        migrations.AddField(
            model_name='bannedidentifier',
            name='is_shadow_ban',
            field=models.BooleanField(default=False, help_text='Shadow ban: user can post but posts are never shown publicly.'),
        ),
        migrations.AddField(
            model_name='confession',
            name='moderation_reason',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='confession',
            name='moderation_status',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending_review', 'Pending Review'), ('rejected', 'Rejected'), ('flagged', 'Flagged')], db_index=True, default='approved', max_length=20),
        ),
    ]
