# Generated by Django 5.2.4 on 2026-05-22 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_confessionratelimit_bannedidentifier_is_shadow_ban_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('distance_from_campus', models.CharField(blank=True, max_length=50)),
                ('rent', models.PositiveIntegerField()),
                ('advance', models.PositiveIntegerField(default=0)),
                ('room_type', models.CharField(choices=[('1bhk', '1 BHK'), ('2bhk', '2 BHK'), ('3bhk', '3 BHK'), ('pg', 'PG'), ('hostel', 'Hostel'), ('shared', 'Shared Room'), ('flatmate', 'Flatmate Needed')], max_length=50)),
                ('furnished_status', models.CharField(choices=[('fully', 'Fully Furnished'), ('semi', 'Semi Furnished'), ('unfurnished', 'Unfurnished')], max_length=50)),
                ('current_occupants', models.PositiveIntegerField(default=0)),
                ('needed_occupants', models.PositiveIntegerField(default=1)),
                ('gender_preference', models.CharField(choices=[('boys', 'Boys Only'), ('girls', 'Girls Only'), ('any', 'Any')], default='any', max_length=20)),
                ('food_preference', models.CharField(blank=True, max_length=100)),
                ('smoking_drinking_preference', models.CharField(blank=True, max_length=100)),
                ('languages_preferred', models.CharField(blank=True, max_length=200)),
                ('available_from_date', models.DateField(blank=True, null=True)),
                ('custom_note', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.roomlisting')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
