# Generated by Django 5.2.4 on 2026-05-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_roomlisting_roomimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomlisting',
            name='contact_info',
            field=models.CharField(blank=True, help_text='Phone number or Instagram ID', max_length=100),
        ),
    ]
