# Generated by Django 5.2.4 on 2026-06-03 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_giveawayentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GiveawayState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('winner_selection_in_progress', models.BooleanField(default=False)),
                ('current_winner_type', models.CharField(choices=[('none', 'None'), ('first', 'First Winner'), ('second', 'Second Winner')], default='none', max_length=20)),
                ('manual_first_winner_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('manual_second_winner_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('show_timer', models.BooleanField(default=False)),
                ('timer_duration', models.PositiveIntegerField(default=30)),
                ('timer_end_time', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Giveaway State',
                'verbose_name_plural': 'Giveaway States',
            },
        ),
        migrations.CreateModel(
            name='GiveawayWinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner_type', models.CharField(choices=[('first', 'First Prize (₹1000)'), ('second', 'Second Prize (₹500)')], max_length=10, unique=True)),
                ('instagram_username', models.CharField(max_length=100)),
                ('won_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giveaway_wins', to=settings.AUTH_USER_MODEL)),
                ('won_by', models.ForeignKey(blank=True, help_text='Admin who selected this winner', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='giveaway_wins_awarded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Giveaway Winner',
                'verbose_name_plural': 'Giveaway Winners',
            },
        ),
    ]
