# Generated by Django 5.2.15 on 2026-06-28 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0054_community_communitymessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='chat_cleared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
