# Generated by Django 5.2.4 on 2026-07-14 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0059_dailyquestion_questionoption_questionsuggestion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnotPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('content', models.TextField(max_length=5000)),
                ('link', models.URLField(blank=True, max_length=1000)),
                ('category', models.CharField(blank=True, choices=[('question', 'Question'), ('advice', 'Advice'), ('information', 'Information'), ('discussion', 'Discussion'), ('resources', 'Resources')], max_length=24)),
                ('college', models.CharField(db_index=True, max_length=80)),
                ('campus', models.CharField(db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knot_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnotEngagementNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_notices', to='home.knotpost')),
            ],
        ),
        migrations.CreateModel(
            name='KnotComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=2000)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='home.knotcomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knot_comments', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='home.knotpost')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnotPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.CharField(choices=[('newest', 'Newest'), ('hot', 'Hot'), ('top', 'Top'), ('oldest', 'Oldest')], default='newest', max_length=10)),
                ('colleges', models.JSONField(blank=True, default=list)),
                ('campuses', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='knot_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KnotReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('harassment', 'Harassment'), ('unsafe', 'Unsafe or harmful'), ('misinformation', 'Misinformation'), ('other', 'Other')], default='other', max_length=24)),
                ('details', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='home.knotcomment')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='home.knotpost')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knot_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KnotVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='home.knotpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knot_votes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KnotCommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='home.knotcomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knot_comment_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('comment', 'user'), name='unique_knot_comment_like')],
            },
        ),
        migrations.AddIndex(
            model_name='knotpost',
            index=models.Index(fields=['college', 'campus', '-created_at'], name='knot_col_camp_new_idx'),
        ),
        migrations.AddConstraint(
            model_name='knotengagementnotice',
            constraint=models.UniqueConstraint(fields=('post', 'threshold'), name='unique_knot_notice'),
        ),
        migrations.AddIndex(
            model_name='knotcomment',
            index=models.Index(fields=['post', 'parent', 'created_at'], name='knot_comment_tree_idx'),
        ),
        migrations.AddConstraint(
            model_name='knotreport',
            constraint=models.UniqueConstraint(condition=models.Q(('post__isnull', False)), fields=('reporter', 'post'), name='unique_knot_post_report'),
        ),
        migrations.AddConstraint(
            model_name='knotreport',
            constraint=models.UniqueConstraint(condition=models.Q(('comment__isnull', False)), fields=('reporter', 'comment'), name='unique_knot_comment_report'),
        ),
        migrations.AddConstraint(
            model_name='knotreport',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('comment__isnull', True), ('post__isnull', False)), models.Q(('comment__isnull', False), ('post__isnull', True)), _connector='OR'), name='knot_report_one_target'),
        ),
        migrations.AddIndex(
            model_name='knotvote',
            index=models.Index(fields=['post', 'created_at'], name='knot_vote_post_idx'),
        ),
        migrations.AddConstraint(
            model_name='knotvote',
            constraint=models.UniqueConstraint(fields=('post', 'user'), name='unique_knot_vote'),
        ),
    ]
