# Generated by Django 5.2.15 on 2026-07-14 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0061_dailymatchaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='knotpost',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='knotpost',
            name='campus',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='knotpost',
            name='college',
            field=models.CharField(blank=True, db_index=True, default='', max_length=80),
        ),
    ]
