


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";





SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."auth_group" (
    "id" integer NOT NULL,
    "name" character varying(150) NOT NULL
);


ALTER TABLE "public"."auth_group" OWNER TO "postgres";


ALTER TABLE "public"."auth_group" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."auth_group_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."auth_group_permissions" (
    "id" bigint NOT NULL,
    "group_id" integer NOT NULL,
    "permission_id" integer NOT NULL
);


ALTER TABLE "public"."auth_group_permissions" OWNER TO "postgres";


ALTER TABLE "public"."auth_group_permissions" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."auth_group_permissions_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."auth_permission" (
    "id" integer NOT NULL,
    "name" character varying(255) NOT NULL,
    "content_type_id" integer NOT NULL,
    "codename" character varying(100) NOT NULL
);


ALTER TABLE "public"."auth_permission" OWNER TO "postgres";


ALTER TABLE "public"."auth_permission" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."auth_permission_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."auth_user" (
    "id" integer NOT NULL,
    "password" character varying(128) NOT NULL,
    "last_login" timestamp with time zone,
    "is_superuser" boolean NOT NULL,
    "username" character varying(150) NOT NULL,
    "first_name" character varying(150) NOT NULL,
    "last_name" character varying(150) NOT NULL,
    "email" character varying(254) NOT NULL,
    "is_staff" boolean NOT NULL,
    "is_active" boolean NOT NULL,
    "date_joined" timestamp with time zone NOT NULL
);


ALTER TABLE "public"."auth_user" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."auth_user_groups" (
    "id" bigint NOT NULL,
    "user_id" integer NOT NULL,
    "group_id" integer NOT NULL
);


ALTER TABLE "public"."auth_user_groups" OWNER TO "postgres";


ALTER TABLE "public"."auth_user_groups" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."auth_user_groups_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE "public"."auth_user" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."auth_user_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."auth_user_user_permissions" (
    "id" bigint NOT NULL,
    "user_id" integer NOT NULL,
    "permission_id" integer NOT NULL
);


ALTER TABLE "public"."auth_user_user_permissions" OWNER TO "postgres";


ALTER TABLE "public"."auth_user_user_permissions" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."auth_user_user_permissions_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."django_admin_log" (
    "id" integer NOT NULL,
    "action_time" timestamp with time zone NOT NULL,
    "object_id" "text",
    "object_repr" character varying(200) NOT NULL,
    "action_flag" smallint NOT NULL,
    "change_message" "text" NOT NULL,
    "content_type_id" integer,
    "user_id" integer NOT NULL,
    CONSTRAINT "django_admin_log_action_flag_check" CHECK (("action_flag" >= 0))
);


ALTER TABLE "public"."django_admin_log" OWNER TO "postgres";


ALTER TABLE "public"."django_admin_log" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."django_admin_log_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."django_content_type" (
    "id" integer NOT NULL,
    "app_label" character varying(100) NOT NULL,
    "model" character varying(100) NOT NULL
);


ALTER TABLE "public"."django_content_type" OWNER TO "postgres";


ALTER TABLE "public"."django_content_type" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."django_content_type_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."django_migrations" (
    "id" bigint NOT NULL,
    "app" character varying(255) NOT NULL,
    "name" character varying(255) NOT NULL,
    "applied" timestamp with time zone NOT NULL
);


ALTER TABLE "public"."django_migrations" OWNER TO "postgres";


ALTER TABLE "public"."django_migrations" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."django_migrations_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."django_session" (
    "session_key" character varying(40) NOT NULL,
    "session_data" "text" NOT NULL,
    "expire_date" timestamp with time zone NOT NULL
);


ALTER TABLE "public"."django_session" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."home_advertisement" (
    "id" bigint NOT NULL,
    "title" character varying(200) NOT NULL,
    "image_url" character varying(500) NOT NULL,
    "link_url" character varying(500) NOT NULL,
    "order" integer NOT NULL,
    "is_active" boolean NOT NULL,
    "created_at" timestamp with time zone NOT NULL
);


ALTER TABLE "public"."home_advertisement" OWNER TO "postgres";


ALTER TABLE "public"."home_advertisement" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."home_advertisement_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."home_announcement" (
    "id" bigint NOT NULL,
    "text" "text" NOT NULL,
    "created_at" timestamp with time zone NOT NULL
);


ALTER TABLE "public"."home_announcement" OWNER TO "postgres";


ALTER TABLE "public"."home_announcement" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."home_announcement_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."home_bannedidentifier" (
    "id" bigint NOT NULL,
    "fingerprint" character varying(100) NOT NULL,
    "reason" "text" NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "is_shadow_ban" boolean NOT NULL
);


ALTER TABLE "public"."home_bannedidentifier" OWNER TO "postgres";


ALTER TABLE "public"."home_bannedidentifier" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."home_bannedidentifier_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."home_blockeduser" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "blocked_id" integer NOT NULL,
    "blocker_id" integer NOT NULL
);


ALTER TABLE "public"."home_blockeduser" OWNER TO "postgres";


ALTER TABLE "public"."home_blockeduser" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."home_blockeduser_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."home_bugreport" (
    "id" bigint NOT NULL,
    "category" character varying(20) NOT NULL,
    "title" character varying(200) NOT NULL,
    "description" "text" NOT NULL,
    "screenshot" character varying(200),
    "device_info" "jsonb",
    "page_url" character varying(500) NOT NULL,
    "status" character varying(20) NOT NULL,
    "admin_reply" "text" NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "updated_at" timestamp with time zone NOT NULL,
    "user_id" integer NOT NULL
);


ALTER TABLE "public"."home_bugreport" OWNER TO "postgres";


ALTER TABLE "public"."home_bugreport" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."home_bugreport_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."home_campusspotlight" (
    "id" bigint NOT NULL,
    "instagram_handle" character varying(100) NOT NULL,
    "content_type" character varying(50) NOT NULL,
    "note" "text" NOT NULL,
    "is_active" boolean NOT NULL,
    "order" integer NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "user_id" integer NOT NULL,
    "cover_image" character varying(500) NOT NULL
);


ALTER TABLE "public"."home_campusspotlight" OWNER TO "postgres";


ALTER TABLE "public"."home_campusspotlight" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."home_campusspotlight_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."home_community" (
    "id" bigint NOT NULL,
    "name" character varying(100) NOT NULL,
    "slug" character varying(50) NOT NULL,
    "description" character varying(255) NOT NULL,
    "image" character varying(500) NOT NULL,
    "member_count" integer NOT NULL,
    "is_anonymous" boolean NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "chat_cleared_at" timestamp with time zone,
    CONSTRAINT "home_community_member_count_check" CHECK (("member_count" >= 0))
);


ALTER TABLE "public"."home_community" OWNER TO "postgres";


ALTER TABLE "public"."home_community" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."home_community_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."home_communitymessage" (
    "id" bigint NOT NULL,
    "text" "text" NOT NULL,
    "timestamp" timestamp with time zone NOT NULL,
    "sender_deleted" boolean NOT NULL,
    "community_id" bigint NOT NULL,
    "reply_to_id" bigint,
    "sender_id" integer NOT NULL
);


ALTER TABLE "public"."home_communitymessage" OWNER TO "postgres";


ALTER TABLE "public"."home_communitymessage" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."home_communitymessage_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."home_confession" (
    "id" bigint NOT NULL,
    "content" "text" NOT NULL,
    "image" character varying(500),
    "campus" character varying(100) NOT NULL,
    "is_anonymous" boolean NOT NULL,
    "likes_count" integer NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "user_id" integer,
    "is_flagged" boolean NOT NULL,
    "poster_fingerprint" character varying(100),
    "moderation_reason" character varying(200) NOT NULL,
    "moderation_status" character varying(20) NOT NULL,
    CONSTRAINT "home_confession_likes_count_check" CHECK (("likes_count" >= 0))
);


ALTER TABLE "public"."home_confession" OWNER TO "postgres";


ALTER TABLE "public"."home_confession" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."home_confession_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."home_confessioncomment" (
    "id" bigint NOT NULL,
    "content" "text" NOT NULL,
    "is_anonymous" boolean NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "confession_id" bigint NOT NULL,
    "user_id" integer,
    "poster_fingerprint" character varying(100)
);


ALTER TABLE "public"."home_confessioncomment" OWNER TO "postgres";


ALTER TABLE "public"."home_confessioncomment" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."home_confessioncomment_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."home_confessionlike" (
    "id" bigint NOT NULL,
    "session_key" character varying(100) NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "confession_id" bigint NOT NULL
);


ALTER TABLE "public"."home_confessionlike" OWNER TO "postgres";


ALTER TABLE "public"."home_confessionlike" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."home_confessionlike_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."home_confessionratelimit" (
    "id" bigint NOT NULL,
    "identifier" character varying(200) NOT NULL,
    "submitted_at" timestamp with time zone NOT NULL
);


ALTER TABLE "public"."home_confessionratelimit" OWNER TO "postgres";


ALTER TABLE "public"."home_confessionratelimit" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."home_confessionratelimit_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."home_confessionreport" (
    "id" bigint NOT NULL,
    "other_reason" "text" NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "confession_id" bigint NOT NULL,
    "user_id" integer,
    "reasons" "jsonb" NOT NULL,
    "reporter_fingerprint" character varying(100)
);


ALTER TABLE "public"."home_confessionreport" OWNER TO "postgres";


ALTER TABLE "public"."home_confessionreport" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."home_confessionreport_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."home_conversation" (
    "id" bigint NOT NULL,
    "source" character varying(50) NOT NULL,
    "listing_id" integer,
    "request_id" integer,
    "created_at" timestamp with time zone NOT NULL,
    "user1_id" integer NOT NULL,
    "user2_id" integer NOT NULL,
    CONSTRAINT "home_conversation_listing_id_check" CHECK (("listing_id" >= 0)),
    CONSTRAINT "home_conversation_request_id_check" CHECK (("request_id" >= 0))
);


ALTER TABLE "public"."home_conversation" OWNER TO "postgres";


ALTER TABLE "public"."home_conversation" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."home_conversation_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."home_dailyloginreward" (
    "id" bigint NOT NULL,
    "date" "date" NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "user_id" integer NOT NULL
);


ALTER TABLE "public"."home_dailyloginreward" OWNER TO "postgres";


ALTER TABLE "public"."home_dailyloginreward" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."home_dailyloginreward_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."home_dailyspark" (
    "id" bigint NOT NULL,
    "date" "date" NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "receiver_id" integer NOT NULL,
    "sender_id" integer NOT NULL
);


ALTER TABLE "public"."home_dailyspark" OWNER TO "postgres";


ALTER TABLE "public"."home_dailyspark" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."home_dailyspark_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."home_event" (
    "id" bigint NOT NULL,
    "title" character varying(200) NOT NULL,
    "poster" character varying(500) NOT NULL,
    "description" "text" NOT NULL,
    "campus" character varying(100) NOT NULL,
    "event_date" "date" NOT NULL,
    "last_reg_date" "date",
    "fee_type" character varying(10) NOT NULL,
    "fee_amount" numeric(10,2),
    "reg_link" character varying(500) NOT NULL,
    "page_link" character varying(500) NOT NULL,
    "status" character varying(10) NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "updated_at" timestamp with time zone NOT NULL,
    "user_id" integer NOT NULL,
    "slug" character varying(255) NOT NULL,
    "location" character varying(200) NOT NULL
);


ALTER TABLE "public"."home_event" OWNER TO "postgres";


ALTER TABLE "public"."home_event" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."home_event_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."home_favoritemovie" (
    "id" bigint NOT NULL,
    "tmdb_id" integer NOT NULL,
    "title" character varying(255) NOT NULL,
    "poster_url" character varying(500),
    "release_year" character varying(10) NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "user_id" integer NOT NULL
);


ALTER TABLE "public"."home_favoritemovie" OWNER TO "postgres";


ALTER TABLE "public"."home_favoritemovie" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."home_favoritemovie_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."home_favoritesong" (
    "id" bigint NOT NULL,
    "itunes_track_id" character varying(100) NOT NULL,
    "title" character varying(255) NOT NULL,
    "artist" character varying(255) NOT NULL,
    "album" character varying(255) NOT NULL,
    "artwork_url" character varying(500),
    "created_at" timestamp with time zone NOT NULL,
    "user_id" integer NOT NULL
);


ALTER TABLE "public"."home_favoritesong" OWNER TO "postgres";


ALTER TABLE "public"."home_favoritesong" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."home_favoritesong_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."home_fcmtoken" (
    "id" bigint NOT NULL,
    "token" character varying(500) NOT NULL,
    "device_type" character varying(20) NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "updated_at" timestamp with time zone NOT NULL,
    "user_id" integer NOT NULL
);


ALTER TABLE "public"."home_fcmtoken" OWNER TO "postgres";


ALTER TABLE "public"."home_fcmtoken" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."home_fcmtoken_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."home_featuresuggestion" (
    "id" bigint NOT NULL,
    "title" character varying(200) NOT NULL,
    "description" "text" NOT NULL,
    "category" character varying(20) NOT NULL,
    "priority" character varying(10) NOT NULL,
    "status" character varying(20) NOT NULL,
    "votes" integer NOT NULL,
    "admin_reply" "text" NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "user_id" integer NOT NULL
);


ALTER TABLE "public"."home_featuresuggestion" OWNER TO "postgres";


ALTER TABLE "public"."home_featuresuggestion" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."home_featuresuggestion_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."home_feedbacknotification" (
    "id" bigint NOT NULL,
    "message" character varying(300) NOT NULL,
    "link" character varying(200) NOT NULL,
    "is_read" boolean NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "user_id" integer NOT NULL
);


ALTER TABLE "public"."home_feedbacknotification" OWNER TO "postgres";


ALTER TABLE "public"."home_feedbacknotification" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."home_feedbacknotification_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."home_giveawayentry" (
    "id" bigint NOT NULL,
    "instagram_username" character varying(100) NOT NULL,
    "followed_confirmed" boolean NOT NULL,
    "shared_confirmed" boolean NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "user_id" integer NOT NULL
);


ALTER TABLE "public"."home_giveawayentry" OWNER TO "postgres";


ALTER TABLE "public"."home_giveawayentry" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."home_giveawayentry_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."home_giveawaystate" (
    "id" bigint NOT NULL,
    "is_active" boolean NOT NULL,
    "winner_selection_in_progress" boolean NOT NULL,
    "current_winner_type" character varying(20) NOT NULL,
    "manual_first_winner_email" character varying(254),
    "manual_second_winner_email" character varying(254),
    "show_timer" boolean NOT NULL,
    "timer_duration" integer NOT NULL,
    "timer_end_time" timestamp with time zone,
    "updated_at" timestamp with time zone NOT NULL,
    "updated_by_id" integer,
    CONSTRAINT "home_giveawaystate_timer_duration_check" CHECK (("timer_duration" >= 0))
);


ALTER TABLE "public"."home_giveawaystate" OWNER TO "postgres";


ALTER TABLE "public"."home_giveawaystate" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."home_giveawaystate_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."home_giveawaywinner" (
    "id" bigint NOT NULL,
    "winner_type" character varying(10) NOT NULL,
    "instagram_username" character varying(100) NOT NULL,
    "won_at" timestamp with time zone NOT NULL,
    "user_id" integer NOT NULL,
    "won_by_id" integer
);


ALTER TABLE "public"."home_giveawaywinner" OWNER TO "postgres";


ALTER TABLE "public"."home_giveawaywinner" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."home_giveawaywinner_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."home_matchrequest" (
    "id" bigint NOT NULL,
    "status" character varying(10) NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "receiver_id" integer NOT NULL,
    "sender_id" integer NOT NULL
);


ALTER TABLE "public"."home_matchrequest" OWNER TO "postgres";


ALTER TABLE "public"."home_matchrequest" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."home_matchrequest_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."home_message" (
    "id" bigint NOT NULL,
    "text" "text" NOT NULL,
    "timestamp" timestamp with time zone NOT NULL,
    "is_read" boolean NOT NULL,
    "receiver_id" integer NOT NULL,
    "sender_id" integer NOT NULL,
    "receiver_deleted" boolean NOT NULL,
    "sender_deleted" boolean NOT NULL,
    "reply_to_id" bigint,
    "image" character varying(500)
);


ALTER TABLE "public"."home_message" OWNER TO "postgres";


ALTER TABLE "public"."home_message" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."home_message_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."home_option" (
    "id" bigint NOT NULL,
    "text" character varying(100) NOT NULL,
    "question_id" bigint NOT NULL,
    "weight" double precision NOT NULL
);


ALTER TABLE "public"."home_option" OWNER TO "postgres";


ALTER TABLE "public"."home_option" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."home_option_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."home_profile" (
    "id" bigint NOT NULL,
    "name" character varying(100) NOT NULL,
    "gender" character varying(10) NOT NULL,
    "profile_pic" character varying(500),
    "age" integer,
    "clg_year" integer,
    "campus" character varying(100) NOT NULL,
    "course" character varying(100) NOT NULL,
    "living_place" character varying(100) NOT NULL,
    "native_place" character varying(100) NOT NULL,
    "languages" "text" NOT NULL,
    "mother_tongues" "text" NOT NULL,
    "bio" "text" NOT NULL,
    "liked_songs" "text" NOT NULL,
    "liked_movies" "text" NOT NULL,
    "fav_shows" "text" NOT NULL,
    "interest_tags" "text" NOT NULL,
    "looking_for" character varying(50) NOT NULL,
    "pref_age_min" integer NOT NULL,
    "pref_age_max" integer NOT NULL,
    "pref_gender" character varying(10) NOT NULL,
    "pref_languages" "text" NOT NULL,
    "pref_campus" character varying(100) NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "updated_at" timestamp with time zone NOT NULL,
    "user_id" integer NOT NULL,
    "is_banned" boolean NOT NULL,
    "is_discoverable" boolean NOT NULL,
    "is_face_verified" boolean NOT NULL,
    "verification_image" character varying(500),
    "verification_status" character varying(20) NOT NULL,
    "total_sparks" integer NOT NULL,
    "quiz_completed" boolean NOT NULL,
    CONSTRAINT "home_profile_age_check" CHECK (("age" >= 0)),
    CONSTRAINT "home_profile_pref_age_max_check" CHECK (("pref_age_max" >= 0)),
    CONSTRAINT "home_profile_pref_age_min_check" CHECK (("pref_age_min" >= 0)),
    CONSTRAINT "home_profile_total_sparks_check" CHECK (("total_sparks" >= 0))
);


ALTER TABLE "public"."home_profile" OWNER TO "postgres";


ALTER TABLE "public"."home_profile" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."home_profile_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."home_profileimage" (
    "id" bigint NOT NULL,
    "image" character varying(500) NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "profile_id" bigint NOT NULL
);


ALTER TABLE "public"."home_profileimage" OWNER TO "postgres";


ALTER TABLE "public"."home_profileimage" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."home_profileimage_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."home_question" (
    "id" bigint NOT NULL,
    "text" character varying(255) NOT NULL
);


ALTER TABLE "public"."home_question" OWNER TO "postgres";


ALTER TABLE "public"."home_question" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."home_question_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."home_roomimage" (
    "id" bigint NOT NULL,
    "image_url" character varying(1000) NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "listing_id" bigint NOT NULL
);


ALTER TABLE "public"."home_roomimage" OWNER TO "postgres";


ALTER TABLE "public"."home_roomimage" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."home_roomimage_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."home_roomlisting" (
    "id" bigint NOT NULL,
    "campus" character varying(100) NOT NULL,
    "location" character varying(200) NOT NULL,
    "distance_from_campus" character varying(50) NOT NULL,
    "rent" integer NOT NULL,
    "advance" integer NOT NULL,
    "room_type" character varying(50) NOT NULL,
    "furnished_status" character varying(50) NOT NULL,
    "current_occupants" integer NOT NULL,
    "needed_occupants" integer NOT NULL,
    "gender_preference" character varying(20) NOT NULL,
    "food_preference" character varying(100) NOT NULL,
    "smoking_drinking_preference" character varying(100) NOT NULL,
    "languages_preferred" character varying(200) NOT NULL,
    "available_from_date" "date",
    "custom_note" "text" NOT NULL,
    "is_active" boolean NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "updated_at" timestamp with time zone NOT NULL,
    "user_id" integer NOT NULL,
    "contact_info" character varying(100) NOT NULL,
    CONSTRAINT "home_roomlisting_advance_check" CHECK (("advance" >= 0)),
    CONSTRAINT "home_roomlisting_current_occupants_check" CHECK (("current_occupants" >= 0)),
    CONSTRAINT "home_roomlisting_needed_occupants_check" CHECK (("needed_occupants" >= 0)),
    CONSTRAINT "home_roomlisting_rent_check" CHECK (("rent" >= 0))
);


ALTER TABLE "public"."home_roomlisting" OWNER TO "postgres";


ALTER TABLE "public"."home_roomlisting" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."home_roomlisting_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."home_roomrequest" (
    "id" bigint NOT NULL,
    "title" character varying(70) NOT NULL,
    "campus" character varying(100) NOT NULL,
    "looking_near" character varying(200) NOT NULL,
    "min_rent" integer NOT NULL,
    "max_rent" integer NOT NULL,
    "preferred_room_type" character varying(50) NOT NULL,
    "sharing_preference" character varying(50) NOT NULL,
    "needed_amenities" character varying(200) NOT NULL,
    "move_in_date" "date" NOT NULL,
    "extra_note" character varying(110) NOT NULL,
    "is_active" boolean NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "updated_at" timestamp with time zone NOT NULL,
    "user_id" integer NOT NULL,
    CONSTRAINT "home_roomrequest_max_rent_check" CHECK (("max_rent" >= 0)),
    CONSTRAINT "home_roomrequest_min_rent_check" CHECK (("min_rent" >= 0))
);


ALTER TABLE "public"."home_roomrequest" OWNER TO "postgres";


ALTER TABLE "public"."home_roomrequest" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."home_roomrequest_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."home_savedroomlisting" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "listing_id" bigint NOT NULL,
    "user_id" integer NOT NULL
);


ALTER TABLE "public"."home_savedroomlisting" OWNER TO "postgres";


ALTER TABLE "public"."home_savedroomlisting" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."home_savedroomlisting_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."home_spark" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "receiver_id" integer NOT NULL,
    "sender_id" integer NOT NULL
);


ALTER TABLE "public"."home_spark" OWNER TO "postgres";


ALTER TABLE "public"."home_spark" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."home_spark_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."home_sparkstreak" (
    "id" bigint NOT NULL,
    "streak" integer NOT NULL,
    "last_spark_date" "date",
    "updated_at" timestamp with time zone NOT NULL,
    "user1_id" integer NOT NULL,
    "user2_id" integer NOT NULL,
    CONSTRAINT "home_sparkstreak_streak_check" CHECK (("streak" >= 0))
);


ALTER TABLE "public"."home_sparkstreak" OWNER TO "postgres";


ALTER TABLE "public"."home_sparkstreak" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."home_sparkstreak_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."home_staffmember" (
    "id" bigint NOT NULL,
    "email" character varying(254) NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "added_by_id" integer
);


ALTER TABLE "public"."home_staffmember" OWNER TO "postgres";


ALTER TABLE "public"."home_staffmember" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."home_staffmember_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."home_supportticket" (
    "id" bigint NOT NULL,
    "subject" character varying(200) NOT NULL,
    "category" character varying(20) NOT NULL,
    "status" character varying(20) NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "updated_at" timestamp with time zone NOT NULL,
    "user_id" integer NOT NULL,
    "unread" integer NOT NULL
);


ALTER TABLE "public"."home_supportticket" OWNER TO "postgres";


ALTER TABLE "public"."home_supportticket" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."home_supportticket_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."home_ticketmessage" (
    "id" bigint NOT NULL,
    "message" "text" NOT NULL,
    "is_admin" boolean NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "sender_id" integer NOT NULL,
    "ticket_id" bigint NOT NULL
);


ALTER TABLE "public"."home_ticketmessage" OWNER TO "postgres";


ALTER TABLE "public"."home_ticketmessage" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."home_ticketmessage_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."home_useranswer" (
    "id" bigint NOT NULL,
    "option_id" bigint NOT NULL,
    "question_id" bigint NOT NULL,
    "user_id" integer NOT NULL
);


ALTER TABLE "public"."home_useranswer" OWNER TO "postgres";


ALTER TABLE "public"."home_useranswer" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."home_useranswer_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."home_userreport" (
    "id" bigint NOT NULL,
    "reasons" "jsonb" NOT NULL,
    "other_reason" "text" NOT NULL,
    "chat_snapshot" "jsonb" NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "reported_user_id" integer NOT NULL,
    "reporter_id" integer NOT NULL
);


ALTER TABLE "public"."home_userreport" OWNER TO "postgres";


ALTER TABLE "public"."home_userreport" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."home_userreport_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."home_voiceparticipant" (
    "id" bigint NOT NULL,
    "joined_at" timestamp with time zone NOT NULL,
    "is_muted" boolean NOT NULL,
    "user_id" integer NOT NULL,
    "room_id" bigint NOT NULL,
    "last_heartbeat" timestamp with time zone,
    "session_peer_id" character varying(50)
);


ALTER TABLE "public"."home_voiceparticipant" OWNER TO "postgres";


ALTER TABLE "public"."home_voiceparticipant" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."home_voiceparticipant_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."home_voiceroom" (
    "id" bigint NOT NULL,
    "name" character varying(100) NOT NULL,
    "slug" character varying(50) NOT NULL,
    "max_capacity" integer NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    CONSTRAINT "home_voiceroom_max_capacity_check" CHECK (("max_capacity" >= 0))
);


ALTER TABLE "public"."home_voiceroom" OWNER TO "postgres";


ALTER TABLE "public"."home_voiceroom" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."home_voiceroom_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."home_wallimage" (
    "id" bigint NOT NULL,
    "image_url" character varying(1000) NOT NULL,
    "x" double precision NOT NULL,
    "y" double precision NOT NULL,
    "width" double precision NOT NULL,
    "height" double precision NOT NULL,
    "created_at" timestamp with time zone NOT NULL
);


ALTER TABLE "public"."home_wallimage" OWNER TO "postgres";


ALTER TABLE "public"."home_wallimage" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."home_wallimage_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."home_wallstroke" (
    "id" bigint NOT NULL,
    "points" "jsonb" NOT NULL,
    "color" character varying(20) NOT NULL,
    "brush_size" double precision NOT NULL,
    "created_at" timestamp with time zone NOT NULL
);


ALTER TABLE "public"."home_wallstroke" OWNER TO "postgres";


ALTER TABLE "public"."home_wallstroke" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."home_wallstroke_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."auth_group"
    ADD CONSTRAINT "auth_group_name_key" UNIQUE ("name");



ALTER TABLE ONLY "public"."auth_group_permissions"
    ADD CONSTRAINT "auth_group_permissions_group_id_permission_id_0cd325b0_uniq" UNIQUE ("group_id", "permission_id");



ALTER TABLE ONLY "public"."auth_group_permissions"
    ADD CONSTRAINT "auth_group_permissions_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."auth_group"
    ADD CONSTRAINT "auth_group_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."auth_permission"
    ADD CONSTRAINT "auth_permission_content_type_id_codename_01ab375a_uniq" UNIQUE ("content_type_id", "codename");



ALTER TABLE ONLY "public"."auth_permission"
    ADD CONSTRAINT "auth_permission_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."auth_user_groups"
    ADD CONSTRAINT "auth_user_groups_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."auth_user_groups"
    ADD CONSTRAINT "auth_user_groups_user_id_group_id_94350c0c_uniq" UNIQUE ("user_id", "group_id");



ALTER TABLE ONLY "public"."auth_user"
    ADD CONSTRAINT "auth_user_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."auth_user_user_permissions"
    ADD CONSTRAINT "auth_user_user_permissions_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."auth_user_user_permissions"
    ADD CONSTRAINT "auth_user_user_permissions_user_id_permission_id_14a6b632_uniq" UNIQUE ("user_id", "permission_id");



ALTER TABLE ONLY "public"."auth_user"
    ADD CONSTRAINT "auth_user_username_key" UNIQUE ("username");



ALTER TABLE ONLY "public"."django_admin_log"
    ADD CONSTRAINT "django_admin_log_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."django_content_type"
    ADD CONSTRAINT "django_content_type_app_label_model_76bd3d3b_uniq" UNIQUE ("app_label", "model");



ALTER TABLE ONLY "public"."django_content_type"
    ADD CONSTRAINT "django_content_type_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."django_migrations"
    ADD CONSTRAINT "django_migrations_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."django_session"
    ADD CONSTRAINT "django_session_pkey" PRIMARY KEY ("session_key");



ALTER TABLE ONLY "public"."home_advertisement"
    ADD CONSTRAINT "home_advertisement_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."home_announcement"
    ADD CONSTRAINT "home_announcement_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."home_bannedidentifier"
    ADD CONSTRAINT "home_bannedidentifier_fingerprint_key" UNIQUE ("fingerprint");



ALTER TABLE ONLY "public"."home_bannedidentifier"
    ADD CONSTRAINT "home_bannedidentifier_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."home_blockeduser"
    ADD CONSTRAINT "home_blockeduser_blocker_id_blocked_id_206c803b_uniq" UNIQUE ("blocker_id", "blocked_id");



ALTER TABLE ONLY "public"."home_blockeduser"
    ADD CONSTRAINT "home_blockeduser_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."home_bugreport"
    ADD CONSTRAINT "home_bugreport_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."home_campusspotlight"
    ADD CONSTRAINT "home_campusspotlight_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."home_community"
    ADD CONSTRAINT "home_community_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."home_community"
    ADD CONSTRAINT "home_community_slug_key" UNIQUE ("slug");



ALTER TABLE ONLY "public"."home_communitymessage"
    ADD CONSTRAINT "home_communitymessage_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."home_confession"
    ADD CONSTRAINT "home_confession_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."home_confessioncomment"
    ADD CONSTRAINT "home_confessioncomment_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."home_confessionlike"
    ADD CONSTRAINT "home_confessionlike_confession_id_session_key_dde5023e_uniq" UNIQUE ("confession_id", "session_key");



ALTER TABLE ONLY "public"."home_confessionlike"
    ADD CONSTRAINT "home_confessionlike_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."home_confessionratelimit"
    ADD CONSTRAINT "home_confessionratelimit_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."home_confessionreport"
    ADD CONSTRAINT "home_confessionreport_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."home_conversation"
    ADD CONSTRAINT "home_conversation_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."home_conversation"
    ADD CONSTRAINT "home_conversation_user1_id_user2_id_24feeaf7_uniq" UNIQUE ("user1_id", "user2_id");



ALTER TABLE ONLY "public"."home_dailyloginreward"
    ADD CONSTRAINT "home_dailyloginreward_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."home_dailyloginreward"
    ADD CONSTRAINT "home_dailyloginreward_user_id_date_6b59748d_uniq" UNIQUE ("user_id", "date");



ALTER TABLE ONLY "public"."home_dailyspark"
    ADD CONSTRAINT "home_dailyspark_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."home_dailyspark"
    ADD CONSTRAINT "home_dailyspark_sender_id_receiver_id_date_4d407c0c_uniq" UNIQUE ("sender_id", "receiver_id", "date");



ALTER TABLE ONLY "public"."home_event"
    ADD CONSTRAINT "home_event_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."home_favoritemovie"
    ADD CONSTRAINT "home_favoritemovie_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."home_favoritesong"
    ADD CONSTRAINT "home_favoritesong_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."home_fcmtoken"
    ADD CONSTRAINT "home_fcmtoken_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."home_fcmtoken"
    ADD CONSTRAINT "home_fcmtoken_token_key" UNIQUE ("token");



ALTER TABLE ONLY "public"."home_featuresuggestion"
    ADD CONSTRAINT "home_featuresuggestion_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."home_feedbacknotification"
    ADD CONSTRAINT "home_feedbacknotification_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."home_giveawayentry"
    ADD CONSTRAINT "home_giveawayentry_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."home_giveawayentry"
    ADD CONSTRAINT "home_giveawayentry_user_id_key" UNIQUE ("user_id");



ALTER TABLE ONLY "public"."home_giveawaystate"
    ADD CONSTRAINT "home_giveawaystate_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."home_giveawaywinner"
    ADD CONSTRAINT "home_giveawaywinner_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."home_giveawaywinner"
    ADD CONSTRAINT "home_giveawaywinner_winner_type_key" UNIQUE ("winner_type");



ALTER TABLE ONLY "public"."home_matchrequest"
    ADD CONSTRAINT "home_matchrequest_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."home_matchrequest"
    ADD CONSTRAINT "home_matchrequest_sender_id_receiver_id_70aaaa49_uniq" UNIQUE ("sender_id", "receiver_id");



ALTER TABLE ONLY "public"."home_message"
    ADD CONSTRAINT "home_message_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."home_option"
    ADD CONSTRAINT "home_option_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."home_profile"
    ADD CONSTRAINT "home_profile_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."home_profile"
    ADD CONSTRAINT "home_profile_user_id_key" UNIQUE ("user_id");



ALTER TABLE ONLY "public"."home_profileimage"
    ADD CONSTRAINT "home_profileimage_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."home_question"
    ADD CONSTRAINT "home_question_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."home_roomimage"
    ADD CONSTRAINT "home_roomimage_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."home_roomlisting"
    ADD CONSTRAINT "home_roomlisting_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."home_roomrequest"
    ADD CONSTRAINT "home_roomrequest_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."home_savedroomlisting"
    ADD CONSTRAINT "home_savedroomlisting_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."home_savedroomlisting"
    ADD CONSTRAINT "home_savedroomlisting_user_id_listing_id_d86a9abc_uniq" UNIQUE ("user_id", "listing_id");



ALTER TABLE ONLY "public"."home_spark"
    ADD CONSTRAINT "home_spark_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."home_spark"
    ADD CONSTRAINT "home_spark_sender_id_receiver_id_baeddf7f_uniq" UNIQUE ("sender_id", "receiver_id");



ALTER TABLE ONLY "public"."home_sparkstreak"
    ADD CONSTRAINT "home_sparkstreak_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."home_sparkstreak"
    ADD CONSTRAINT "home_sparkstreak_user1_id_user2_id_e84051bb_uniq" UNIQUE ("user1_id", "user2_id");



ALTER TABLE ONLY "public"."home_staffmember"
    ADD CONSTRAINT "home_staffmember_email_key" UNIQUE ("email");



ALTER TABLE ONLY "public"."home_staffmember"
    ADD CONSTRAINT "home_staffmember_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."home_supportticket"
    ADD CONSTRAINT "home_supportticket_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."home_ticketmessage"
    ADD CONSTRAINT "home_ticketmessage_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."home_useranswer"
    ADD CONSTRAINT "home_useranswer_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."home_useranswer"
    ADD CONSTRAINT "home_useranswer_user_id_question_id_479d61ae_uniq" UNIQUE ("user_id", "question_id");



ALTER TABLE ONLY "public"."home_userreport"
    ADD CONSTRAINT "home_userreport_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."home_voiceparticipant"
    ADD CONSTRAINT "home_voiceparticipant_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."home_voiceparticipant"
    ADD CONSTRAINT "home_voiceparticipant_user_id_room_id_96b61ad5_uniq" UNIQUE ("user_id", "room_id");



ALTER TABLE ONLY "public"."home_voiceroom"
    ADD CONSTRAINT "home_voiceroom_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."home_voiceroom"
    ADD CONSTRAINT "home_voiceroom_slug_key" UNIQUE ("slug");



ALTER TABLE ONLY "public"."home_wallimage"
    ADD CONSTRAINT "home_wallimage_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."home_wallstroke"
    ADD CONSTRAINT "home_wallstroke_pkey" PRIMARY KEY ("id");



CREATE INDEX "auth_group_name_a6ea08ec_like" ON "public"."auth_group" USING "btree" ("name" "varchar_pattern_ops");



CREATE INDEX "auth_group_permissions_group_id_b120cbf9" ON "public"."auth_group_permissions" USING "btree" ("group_id");



CREATE INDEX "auth_group_permissions_permission_id_84c5c92e" ON "public"."auth_group_permissions" USING "btree" ("permission_id");



CREATE INDEX "auth_permission_content_type_id_2f476e4b" ON "public"."auth_permission" USING "btree" ("content_type_id");



CREATE INDEX "auth_user_groups_group_id_97559544" ON "public"."auth_user_groups" USING "btree" ("group_id");



CREATE INDEX "auth_user_groups_user_id_6a12ed8b" ON "public"."auth_user_groups" USING "btree" ("user_id");



CREATE INDEX "auth_user_user_permissions_permission_id_1fbb5f2c" ON "public"."auth_user_user_permissions" USING "btree" ("permission_id");



CREATE INDEX "auth_user_user_permissions_user_id_a95ead1b" ON "public"."auth_user_user_permissions" USING "btree" ("user_id");



CREATE INDEX "auth_user_username_6821ab7c_like" ON "public"."auth_user" USING "btree" ("username" "varchar_pattern_ops");



CREATE INDEX "django_admin_log_content_type_id_c4bce8eb" ON "public"."django_admin_log" USING "btree" ("content_type_id");



CREATE INDEX "django_admin_log_user_id_c564eba6" ON "public"."django_admin_log" USING "btree" ("user_id");



CREATE INDEX "django_session_expire_date_a5c62663" ON "public"."django_session" USING "btree" ("expire_date");



CREATE INDEX "django_session_session_key_c0390e0f_like" ON "public"."django_session" USING "btree" ("session_key" "varchar_pattern_ops");



CREATE INDEX "home_bannedidentifier_fingerprint_431ff789_like" ON "public"."home_bannedidentifier" USING "btree" ("fingerprint" "varchar_pattern_ops");



CREATE INDEX "home_blockeduser_blocked_id_dd5785fa" ON "public"."home_blockeduser" USING "btree" ("blocked_id");



CREATE INDEX "home_blockeduser_blocker_id_a0d1a209" ON "public"."home_blockeduser" USING "btree" ("blocker_id");



CREATE INDEX "home_bugreport_user_id_fe3ed0a8" ON "public"."home_bugreport" USING "btree" ("user_id");



CREATE INDEX "home_campusspotlight_user_id_18dda4fe" ON "public"."home_campusspotlight" USING "btree" ("user_id");



CREATE INDEX "home_community_slug_570fbaeb_like" ON "public"."home_community" USING "btree" ("slug" "varchar_pattern_ops");



CREATE INDEX "home_communitymessage_community_id_090e00fa" ON "public"."home_communitymessage" USING "btree" ("community_id");



CREATE INDEX "home_communitymessage_reply_to_id_7400f488" ON "public"."home_communitymessage" USING "btree" ("reply_to_id");



CREATE INDEX "home_communitymessage_sender_id_92e8dceb" ON "public"."home_communitymessage" USING "btree" ("sender_id");



CREATE INDEX "home_confession_moderation_status_c2568a4b" ON "public"."home_confession" USING "btree" ("moderation_status");



CREATE INDEX "home_confession_moderation_status_c2568a4b_like" ON "public"."home_confession" USING "btree" ("moderation_status" "varchar_pattern_ops");



CREATE INDEX "home_confession_user_id_7ff8cf03" ON "public"."home_confession" USING "btree" ("user_id");



CREATE INDEX "home_confessioncomment_confession_id_1e06e0a6" ON "public"."home_confessioncomment" USING "btree" ("confession_id");



CREATE INDEX "home_confessioncomment_user_id_de82d747" ON "public"."home_confessioncomment" USING "btree" ("user_id");



CREATE INDEX "home_confessionlike_confession_id_7dd9f420" ON "public"."home_confessionlike" USING "btree" ("confession_id");



CREATE INDEX "home_confessionratelimit_identifier_0b9457df" ON "public"."home_confessionratelimit" USING "btree" ("identifier");



CREATE INDEX "home_confessionratelimit_identifier_0b9457df_like" ON "public"."home_confessionratelimit" USING "btree" ("identifier" "varchar_pattern_ops");



CREATE INDEX "home_confessionreport_confession_id_21e85fec" ON "public"."home_confessionreport" USING "btree" ("confession_id");



CREATE INDEX "home_confessionreport_user_id_7937843a" ON "public"."home_confessionreport" USING "btree" ("user_id");



CREATE INDEX "home_conversation_user1_id_5396f63e" ON "public"."home_conversation" USING "btree" ("user1_id");



CREATE INDEX "home_conversation_user2_id_d398a317" ON "public"."home_conversation" USING "btree" ("user2_id");



CREATE INDEX "home_dailyloginreward_user_id_09c2ff75" ON "public"."home_dailyloginreward" USING "btree" ("user_id");



CREATE INDEX "home_dailyspark_receiver_id_13a52f98" ON "public"."home_dailyspark" USING "btree" ("receiver_id");



CREATE INDEX "home_dailyspark_sender_id_ed8d5110" ON "public"."home_dailyspark" USING "btree" ("sender_id");



CREATE UNIQUE INDEX "home_event_slug_key" ON "public"."home_event" USING "btree" ("slug");



CREATE INDEX "home_event_user_id_f3d0a6ac" ON "public"."home_event" USING "btree" ("user_id");



CREATE INDEX "home_favoritemovie_user_id_a06a7fc4" ON "public"."home_favoritemovie" USING "btree" ("user_id");



CREATE INDEX "home_favoritesong_user_id_7c59701b" ON "public"."home_favoritesong" USING "btree" ("user_id");



CREATE INDEX "home_fcmtoken_token_be0c3a4e_like" ON "public"."home_fcmtoken" USING "btree" ("token" "varchar_pattern_ops");



CREATE INDEX "home_fcmtoken_user_id_f76fddc0" ON "public"."home_fcmtoken" USING "btree" ("user_id");



CREATE INDEX "home_featuresuggestion_user_id_74ac49a6" ON "public"."home_featuresuggestion" USING "btree" ("user_id");



CREATE INDEX "home_feedbacknotification_user_id_d99ad779" ON "public"."home_feedbacknotification" USING "btree" ("user_id");



CREATE INDEX "home_giveawaystate_updated_by_id_c27e367d" ON "public"."home_giveawaystate" USING "btree" ("updated_by_id");



CREATE INDEX "home_giveawaywinner_user_id_96d52e62" ON "public"."home_giveawaywinner" USING "btree" ("user_id");



CREATE INDEX "home_giveawaywinner_winner_type_ead72c5c_like" ON "public"."home_giveawaywinner" USING "btree" ("winner_type" "varchar_pattern_ops");



CREATE INDEX "home_giveawaywinner_won_by_id_2f2d2a6f" ON "public"."home_giveawaywinner" USING "btree" ("won_by_id");



CREATE INDEX "home_matchrequest_receiver_id_f6d26d0c" ON "public"."home_matchrequest" USING "btree" ("receiver_id");



CREATE INDEX "home_matchrequest_sender_id_bed6fe9f" ON "public"."home_matchrequest" USING "btree" ("sender_id");



CREATE INDEX "home_message_receiver_id_cbdf13e7" ON "public"."home_message" USING "btree" ("receiver_id");



CREATE INDEX "home_message_reply_to_id_aa5e48c7" ON "public"."home_message" USING "btree" ("reply_to_id");



CREATE INDEX "home_message_sender_id_36db3490" ON "public"."home_message" USING "btree" ("sender_id");



CREATE INDEX "home_option_question_id_e79298e6" ON "public"."home_option" USING "btree" ("question_id");



CREATE INDEX "home_profileimage_profile_id_5a23f7ef" ON "public"."home_profileimage" USING "btree" ("profile_id");



CREATE INDEX "home_roomimage_listing_id_d112c6a3" ON "public"."home_roomimage" USING "btree" ("listing_id");



CREATE INDEX "home_roomlisting_user_id_9c74319d" ON "public"."home_roomlisting" USING "btree" ("user_id");



CREATE INDEX "home_roomrequest_user_id_4b67bbf9" ON "public"."home_roomrequest" USING "btree" ("user_id");



CREATE INDEX "home_savedroomlisting_listing_id_351414c7" ON "public"."home_savedroomlisting" USING "btree" ("listing_id");



CREATE INDEX "home_savedroomlisting_user_id_75852c93" ON "public"."home_savedroomlisting" USING "btree" ("user_id");



CREATE INDEX "home_spark_receiver_id_ad0c241f" ON "public"."home_spark" USING "btree" ("receiver_id");



CREATE INDEX "home_spark_sender_id_28b2519f" ON "public"."home_spark" USING "btree" ("sender_id");



CREATE INDEX "home_sparkstreak_user1_id_e5f94c36" ON "public"."home_sparkstreak" USING "btree" ("user1_id");



CREATE INDEX "home_sparkstreak_user2_id_e9c13e8e" ON "public"."home_sparkstreak" USING "btree" ("user2_id");



CREATE INDEX "home_staffmember_added_by_id_00ef905a" ON "public"."home_staffmember" USING "btree" ("added_by_id");



CREATE INDEX "home_staffmember_email_7b6f6b77_like" ON "public"."home_staffmember" USING "btree" ("email" "varchar_pattern_ops");



CREATE INDEX "home_supportticket_user_id_7c5a38d6" ON "public"."home_supportticket" USING "btree" ("user_id");



CREATE INDEX "home_ticketmessage_sender_id_ba938dd5" ON "public"."home_ticketmessage" USING "btree" ("sender_id");



CREATE INDEX "home_ticketmessage_ticket_id_7b6fd90d" ON "public"."home_ticketmessage" USING "btree" ("ticket_id");



CREATE INDEX "home_useranswer_option_id_942d047c" ON "public"."home_useranswer" USING "btree" ("option_id");



CREATE INDEX "home_useranswer_question_id_6e054301" ON "public"."home_useranswer" USING "btree" ("question_id");



CREATE INDEX "home_useranswer_user_id_b9f38ba9" ON "public"."home_useranswer" USING "btree" ("user_id");



CREATE INDEX "home_userreport_reported_user_id_d0c9b943" ON "public"."home_userreport" USING "btree" ("reported_user_id");



CREATE INDEX "home_userreport_reporter_id_b7a730bc" ON "public"."home_userreport" USING "btree" ("reporter_id");



CREATE INDEX "home_voiceparticipant_room_id_adbc1e70" ON "public"."home_voiceparticipant" USING "btree" ("room_id");



CREATE INDEX "home_voiceparticipant_user_id_e28c1f86" ON "public"."home_voiceparticipant" USING "btree" ("user_id");



CREATE INDEX "home_voiceroom_slug_0c5e4d21_like" ON "public"."home_voiceroom" USING "btree" ("slug" "varchar_pattern_ops");



ALTER TABLE ONLY "public"."auth_group_permissions"
    ADD CONSTRAINT "auth_group_permissio_permission_id_84c5c92e_fk_auth_perm" FOREIGN KEY ("permission_id") REFERENCES "public"."auth_permission"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."auth_group_permissions"
    ADD CONSTRAINT "auth_group_permissions_group_id_b120cbf9_fk_auth_group_id" FOREIGN KEY ("group_id") REFERENCES "public"."auth_group"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."auth_permission"
    ADD CONSTRAINT "auth_permission_content_type_id_2f476e4b_fk_django_co" FOREIGN KEY ("content_type_id") REFERENCES "public"."django_content_type"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."auth_user_groups"
    ADD CONSTRAINT "auth_user_groups_group_id_97559544_fk_auth_group_id" FOREIGN KEY ("group_id") REFERENCES "public"."auth_group"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."auth_user_groups"
    ADD CONSTRAINT "auth_user_groups_user_id_6a12ed8b_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "public"."auth_user"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."auth_user_user_permissions"
    ADD CONSTRAINT "auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm" FOREIGN KEY ("permission_id") REFERENCES "public"."auth_permission"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."auth_user_user_permissions"
    ADD CONSTRAINT "auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "public"."auth_user"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."django_admin_log"
    ADD CONSTRAINT "django_admin_log_content_type_id_c4bce8eb_fk_django_co" FOREIGN KEY ("content_type_id") REFERENCES "public"."django_content_type"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."django_admin_log"
    ADD CONSTRAINT "django_admin_log_user_id_c564eba6_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "public"."auth_user"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."home_blockeduser"
    ADD CONSTRAINT "home_blockeduser_blocked_id_dd5785fa_fk_auth_user_id" FOREIGN KEY ("blocked_id") REFERENCES "public"."auth_user"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."home_blockeduser"
    ADD CONSTRAINT "home_blockeduser_blocker_id_a0d1a209_fk_auth_user_id" FOREIGN KEY ("blocker_id") REFERENCES "public"."auth_user"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."home_bugreport"
    ADD CONSTRAINT "home_bugreport_user_id_fe3ed0a8_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "public"."auth_user"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."home_campusspotlight"
    ADD CONSTRAINT "home_campusspotlight_user_id_18dda4fe_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "public"."auth_user"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."home_communitymessage"
    ADD CONSTRAINT "home_communitymessag_community_id_090e00fa_fk_home_comm" FOREIGN KEY ("community_id") REFERENCES "public"."home_community"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."home_communitymessage"
    ADD CONSTRAINT "home_communitymessag_reply_to_id_7400f488_fk_home_comm" FOREIGN KEY ("reply_to_id") REFERENCES "public"."home_communitymessage"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."home_communitymessage"
    ADD CONSTRAINT "home_communitymessage_sender_id_92e8dceb_fk_auth_user_id" FOREIGN KEY ("sender_id") REFERENCES "public"."auth_user"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."home_confession"
    ADD CONSTRAINT "home_confession_user_id_7ff8cf03_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "public"."auth_user"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."home_confessioncomment"
    ADD CONSTRAINT "home_confessioncomme_confession_id_1e06e0a6_fk_home_conf" FOREIGN KEY ("confession_id") REFERENCES "public"."home_confession"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."home_confessioncomment"
    ADD CONSTRAINT "home_confessioncomment_user_id_de82d747_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "public"."auth_user"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."home_confessionlike"
    ADD CONSTRAINT "home_confessionlike_confession_id_7dd9f420_fk_home_conf" FOREIGN KEY ("confession_id") REFERENCES "public"."home_confession"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."home_confessionreport"
    ADD CONSTRAINT "home_confessionrepor_confession_id_21e85fec_fk_home_conf" FOREIGN KEY ("confession_id") REFERENCES "public"."home_confession"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."home_confessionreport"
    ADD CONSTRAINT "home_confessionreport_user_id_7937843a_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "public"."auth_user"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."home_conversation"
    ADD CONSTRAINT "home_conversation_user1_id_5396f63e_fk_auth_user_id" FOREIGN KEY ("user1_id") REFERENCES "public"."auth_user"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."home_conversation"
    ADD CONSTRAINT "home_conversation_user2_id_d398a317_fk_auth_user_id" FOREIGN KEY ("user2_id") REFERENCES "public"."auth_user"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."home_dailyloginreward"
    ADD CONSTRAINT "home_dailyloginreward_user_id_09c2ff75_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "public"."auth_user"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."home_dailyspark"
    ADD CONSTRAINT "home_dailyspark_receiver_id_13a52f98_fk_auth_user_id" FOREIGN KEY ("receiver_id") REFERENCES "public"."auth_user"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."home_dailyspark"
    ADD CONSTRAINT "home_dailyspark_sender_id_ed8d5110_fk_auth_user_id" FOREIGN KEY ("sender_id") REFERENCES "public"."auth_user"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."home_event"
    ADD CONSTRAINT "home_event_user_id_f3d0a6ac_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "public"."auth_user"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."home_favoritemovie"
    ADD CONSTRAINT "home_favoritemovie_user_id_a06a7fc4_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "public"."auth_user"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."home_favoritesong"
    ADD CONSTRAINT "home_favoritesong_user_id_7c59701b_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "public"."auth_user"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."home_fcmtoken"
    ADD CONSTRAINT "home_fcmtoken_user_id_f76fddc0_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "public"."auth_user"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."home_featuresuggestion"
    ADD CONSTRAINT "home_featuresuggestion_user_id_74ac49a6_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "public"."auth_user"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."home_feedbacknotification"
    ADD CONSTRAINT "home_feedbacknotification_user_id_d99ad779_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "public"."auth_user"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."home_giveawayentry"
    ADD CONSTRAINT "home_giveawayentry_user_id_815cfb6f_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "public"."auth_user"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."home_giveawaystate"
    ADD CONSTRAINT "home_giveawaystate_updated_by_id_c27e367d_fk_auth_user_id" FOREIGN KEY ("updated_by_id") REFERENCES "public"."auth_user"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."home_giveawaywinner"
    ADD CONSTRAINT "home_giveawaywinner_user_id_96d52e62_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "public"."auth_user"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."home_giveawaywinner"
    ADD CONSTRAINT "home_giveawaywinner_won_by_id_2f2d2a6f_fk_auth_user_id" FOREIGN KEY ("won_by_id") REFERENCES "public"."auth_user"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."home_matchrequest"
    ADD CONSTRAINT "home_matchrequest_receiver_id_f6d26d0c_fk_auth_user_id" FOREIGN KEY ("receiver_id") REFERENCES "public"."auth_user"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."home_matchrequest"
    ADD CONSTRAINT "home_matchrequest_sender_id_bed6fe9f_fk_auth_user_id" FOREIGN KEY ("sender_id") REFERENCES "public"."auth_user"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."home_message"
    ADD CONSTRAINT "home_message_receiver_id_cbdf13e7_fk_auth_user_id" FOREIGN KEY ("receiver_id") REFERENCES "public"."auth_user"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."home_message"
    ADD CONSTRAINT "home_message_reply_to_id_aa5e48c7_fk_home_message_id" FOREIGN KEY ("reply_to_id") REFERENCES "public"."home_message"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."home_message"
    ADD CONSTRAINT "home_message_sender_id_36db3490_fk_auth_user_id" FOREIGN KEY ("sender_id") REFERENCES "public"."auth_user"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."home_option"
    ADD CONSTRAINT "home_option_question_id_e79298e6_fk_home_question_id" FOREIGN KEY ("question_id") REFERENCES "public"."home_question"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."home_profile"
    ADD CONSTRAINT "home_profile_user_id_5bf46ea0_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "public"."auth_user"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."home_profileimage"
    ADD CONSTRAINT "home_profileimage_profile_id_5a23f7ef_fk_home_profile_id" FOREIGN KEY ("profile_id") REFERENCES "public"."home_profile"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."home_roomimage"
    ADD CONSTRAINT "home_roomimage_listing_id_d112c6a3_fk_home_roomlisting_id" FOREIGN KEY ("listing_id") REFERENCES "public"."home_roomlisting"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."home_roomlisting"
    ADD CONSTRAINT "home_roomlisting_user_id_9c74319d_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "public"."auth_user"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."home_roomrequest"
    ADD CONSTRAINT "home_roomrequest_user_id_4b67bbf9_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "public"."auth_user"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."home_savedroomlisting"
    ADD CONSTRAINT "home_savedroomlistin_listing_id_351414c7_fk_home_room" FOREIGN KEY ("listing_id") REFERENCES "public"."home_roomlisting"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."home_savedroomlisting"
    ADD CONSTRAINT "home_savedroomlisting_user_id_75852c93_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "public"."auth_user"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."home_spark"
    ADD CONSTRAINT "home_spark_receiver_id_ad0c241f_fk_auth_user_id" FOREIGN KEY ("receiver_id") REFERENCES "public"."auth_user"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."home_spark"
    ADD CONSTRAINT "home_spark_sender_id_28b2519f_fk_auth_user_id" FOREIGN KEY ("sender_id") REFERENCES "public"."auth_user"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."home_sparkstreak"
    ADD CONSTRAINT "home_sparkstreak_user1_id_e5f94c36_fk_auth_user_id" FOREIGN KEY ("user1_id") REFERENCES "public"."auth_user"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."home_sparkstreak"
    ADD CONSTRAINT "home_sparkstreak_user2_id_e9c13e8e_fk_auth_user_id" FOREIGN KEY ("user2_id") REFERENCES "public"."auth_user"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."home_staffmember"
    ADD CONSTRAINT "home_staffmember_added_by_id_00ef905a_fk_auth_user_id" FOREIGN KEY ("added_by_id") REFERENCES "public"."auth_user"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."home_supportticket"
    ADD CONSTRAINT "home_supportticket_user_id_7c5a38d6_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "public"."auth_user"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."home_ticketmessage"
    ADD CONSTRAINT "home_ticketmessage_sender_id_ba938dd5_fk_auth_user_id" FOREIGN KEY ("sender_id") REFERENCES "public"."auth_user"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."home_ticketmessage"
    ADD CONSTRAINT "home_ticketmessage_ticket_id_7b6fd90d_fk_home_supportticket_id" FOREIGN KEY ("ticket_id") REFERENCES "public"."home_supportticket"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."home_useranswer"
    ADD CONSTRAINT "home_useranswer_option_id_942d047c_fk_home_option_id" FOREIGN KEY ("option_id") REFERENCES "public"."home_option"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."home_useranswer"
    ADD CONSTRAINT "home_useranswer_question_id_6e054301_fk_home_question_id" FOREIGN KEY ("question_id") REFERENCES "public"."home_question"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."home_useranswer"
    ADD CONSTRAINT "home_useranswer_user_id_b9f38ba9_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "public"."auth_user"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."home_userreport"
    ADD CONSTRAINT "home_userreport_reported_user_id_d0c9b943_fk_auth_user_id" FOREIGN KEY ("reported_user_id") REFERENCES "public"."auth_user"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."home_userreport"
    ADD CONSTRAINT "home_userreport_reporter_id_b7a730bc_fk_auth_user_id" FOREIGN KEY ("reporter_id") REFERENCES "public"."auth_user"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."home_voiceparticipant"
    ADD CONSTRAINT "home_voiceparticipant_room_id_adbc1e70_fk_home_voiceroom_id" FOREIGN KEY ("room_id") REFERENCES "public"."home_voiceroom"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."home_voiceparticipant"
    ADD CONSTRAINT "home_voiceparticipant_user_id_e28c1f86_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "public"."auth_user"("id") DEFERRABLE INITIALLY DEFERRED;





ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";





































































































































































GRANT ALL ON TABLE "public"."auth_group" TO "anon";
GRANT ALL ON TABLE "public"."auth_group" TO "authenticated";
GRANT ALL ON TABLE "public"."auth_group" TO "service_role";



GRANT ALL ON SEQUENCE "public"."auth_group_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."auth_group_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."auth_group_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."auth_group_permissions" TO "anon";
GRANT ALL ON TABLE "public"."auth_group_permissions" TO "authenticated";
GRANT ALL ON TABLE "public"."auth_group_permissions" TO "service_role";



GRANT ALL ON SEQUENCE "public"."auth_group_permissions_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."auth_group_permissions_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."auth_group_permissions_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."auth_permission" TO "anon";
GRANT ALL ON TABLE "public"."auth_permission" TO "authenticated";
GRANT ALL ON TABLE "public"."auth_permission" TO "service_role";



GRANT ALL ON SEQUENCE "public"."auth_permission_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."auth_permission_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."auth_permission_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."auth_user" TO "anon";
GRANT ALL ON TABLE "public"."auth_user" TO "authenticated";
GRANT ALL ON TABLE "public"."auth_user" TO "service_role";



GRANT ALL ON TABLE "public"."auth_user_groups" TO "anon";
GRANT ALL ON TABLE "public"."auth_user_groups" TO "authenticated";
GRANT ALL ON TABLE "public"."auth_user_groups" TO "service_role";



GRANT ALL ON SEQUENCE "public"."auth_user_groups_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."auth_user_groups_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."auth_user_groups_id_seq" TO "service_role";



GRANT ALL ON SEQUENCE "public"."auth_user_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."auth_user_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."auth_user_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."auth_user_user_permissions" TO "anon";
GRANT ALL ON TABLE "public"."auth_user_user_permissions" TO "authenticated";
GRANT ALL ON TABLE "public"."auth_user_user_permissions" TO "service_role";



GRANT ALL ON SEQUENCE "public"."auth_user_user_permissions_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."auth_user_user_permissions_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."auth_user_user_permissions_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."django_admin_log" TO "anon";
GRANT ALL ON TABLE "public"."django_admin_log" TO "authenticated";
GRANT ALL ON TABLE "public"."django_admin_log" TO "service_role";



GRANT ALL ON SEQUENCE "public"."django_admin_log_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."django_admin_log_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."django_admin_log_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."django_content_type" TO "anon";
GRANT ALL ON TABLE "public"."django_content_type" TO "authenticated";
GRANT ALL ON TABLE "public"."django_content_type" TO "service_role";



GRANT ALL ON SEQUENCE "public"."django_content_type_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."django_content_type_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."django_content_type_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."django_migrations" TO "anon";
GRANT ALL ON TABLE "public"."django_migrations" TO "authenticated";
GRANT ALL ON TABLE "public"."django_migrations" TO "service_role";



GRANT ALL ON SEQUENCE "public"."django_migrations_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."django_migrations_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."django_migrations_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."django_session" TO "anon";
GRANT ALL ON TABLE "public"."django_session" TO "authenticated";
GRANT ALL ON TABLE "public"."django_session" TO "service_role";



GRANT ALL ON TABLE "public"."home_advertisement" TO "anon";
GRANT ALL ON TABLE "public"."home_advertisement" TO "authenticated";
GRANT ALL ON TABLE "public"."home_advertisement" TO "service_role";



GRANT ALL ON SEQUENCE "public"."home_advertisement_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."home_advertisement_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."home_advertisement_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."home_announcement" TO "anon";
GRANT ALL ON TABLE "public"."home_announcement" TO "authenticated";
GRANT ALL ON TABLE "public"."home_announcement" TO "service_role";



GRANT ALL ON SEQUENCE "public"."home_announcement_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."home_announcement_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."home_announcement_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."home_bannedidentifier" TO "anon";
GRANT ALL ON TABLE "public"."home_bannedidentifier" TO "authenticated";
GRANT ALL ON TABLE "public"."home_bannedidentifier" TO "service_role";



GRANT ALL ON SEQUENCE "public"."home_bannedidentifier_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."home_bannedidentifier_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."home_bannedidentifier_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."home_blockeduser" TO "anon";
GRANT ALL ON TABLE "public"."home_blockeduser" TO "authenticated";
GRANT ALL ON TABLE "public"."home_blockeduser" TO "service_role";



GRANT ALL ON SEQUENCE "public"."home_blockeduser_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."home_blockeduser_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."home_blockeduser_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."home_bugreport" TO "anon";
GRANT ALL ON TABLE "public"."home_bugreport" TO "authenticated";
GRANT ALL ON TABLE "public"."home_bugreport" TO "service_role";



GRANT ALL ON SEQUENCE "public"."home_bugreport_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."home_bugreport_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."home_bugreport_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."home_campusspotlight" TO "anon";
GRANT ALL ON TABLE "public"."home_campusspotlight" TO "authenticated";
GRANT ALL ON TABLE "public"."home_campusspotlight" TO "service_role";



GRANT ALL ON SEQUENCE "public"."home_campusspotlight_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."home_campusspotlight_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."home_campusspotlight_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."home_community" TO "anon";
GRANT ALL ON TABLE "public"."home_community" TO "authenticated";
GRANT ALL ON TABLE "public"."home_community" TO "service_role";



GRANT ALL ON SEQUENCE "public"."home_community_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."home_community_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."home_community_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."home_communitymessage" TO "anon";
GRANT ALL ON TABLE "public"."home_communitymessage" TO "authenticated";
GRANT ALL ON TABLE "public"."home_communitymessage" TO "service_role";



GRANT ALL ON SEQUENCE "public"."home_communitymessage_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."home_communitymessage_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."home_communitymessage_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."home_confession" TO "anon";
GRANT ALL ON TABLE "public"."home_confession" TO "authenticated";
GRANT ALL ON TABLE "public"."home_confession" TO "service_role";



GRANT ALL ON SEQUENCE "public"."home_confession_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."home_confession_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."home_confession_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."home_confessioncomment" TO "anon";
GRANT ALL ON TABLE "public"."home_confessioncomment" TO "authenticated";
GRANT ALL ON TABLE "public"."home_confessioncomment" TO "service_role";



GRANT ALL ON SEQUENCE "public"."home_confessioncomment_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."home_confessioncomment_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."home_confessioncomment_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."home_confessionlike" TO "anon";
GRANT ALL ON TABLE "public"."home_confessionlike" TO "authenticated";
GRANT ALL ON TABLE "public"."home_confessionlike" TO "service_role";



GRANT ALL ON SEQUENCE "public"."home_confessionlike_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."home_confessionlike_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."home_confessionlike_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."home_confessionratelimit" TO "anon";
GRANT ALL ON TABLE "public"."home_confessionratelimit" TO "authenticated";
GRANT ALL ON TABLE "public"."home_confessionratelimit" TO "service_role";



GRANT ALL ON SEQUENCE "public"."home_confessionratelimit_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."home_confessionratelimit_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."home_confessionratelimit_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."home_confessionreport" TO "anon";
GRANT ALL ON TABLE "public"."home_confessionreport" TO "authenticated";
GRANT ALL ON TABLE "public"."home_confessionreport" TO "service_role";



GRANT ALL ON SEQUENCE "public"."home_confessionreport_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."home_confessionreport_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."home_confessionreport_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."home_conversation" TO "anon";
GRANT ALL ON TABLE "public"."home_conversation" TO "authenticated";
GRANT ALL ON TABLE "public"."home_conversation" TO "service_role";



GRANT ALL ON SEQUENCE "public"."home_conversation_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."home_conversation_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."home_conversation_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."home_dailyloginreward" TO "anon";
GRANT ALL ON TABLE "public"."home_dailyloginreward" TO "authenticated";
GRANT ALL ON TABLE "public"."home_dailyloginreward" TO "service_role";



GRANT ALL ON SEQUENCE "public"."home_dailyloginreward_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."home_dailyloginreward_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."home_dailyloginreward_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."home_dailyspark" TO "anon";
GRANT ALL ON TABLE "public"."home_dailyspark" TO "authenticated";
GRANT ALL ON TABLE "public"."home_dailyspark" TO "service_role";



GRANT ALL ON SEQUENCE "public"."home_dailyspark_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."home_dailyspark_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."home_dailyspark_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."home_event" TO "anon";
GRANT ALL ON TABLE "public"."home_event" TO "authenticated";
GRANT ALL ON TABLE "public"."home_event" TO "service_role";



GRANT ALL ON SEQUENCE "public"."home_event_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."home_event_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."home_event_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."home_favoritemovie" TO "anon";
GRANT ALL ON TABLE "public"."home_favoritemovie" TO "authenticated";
GRANT ALL ON TABLE "public"."home_favoritemovie" TO "service_role";



GRANT ALL ON SEQUENCE "public"."home_favoritemovie_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."home_favoritemovie_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."home_favoritemovie_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."home_favoritesong" TO "anon";
GRANT ALL ON TABLE "public"."home_favoritesong" TO "authenticated";
GRANT ALL ON TABLE "public"."home_favoritesong" TO "service_role";



GRANT ALL ON SEQUENCE "public"."home_favoritesong_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."home_favoritesong_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."home_favoritesong_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."home_fcmtoken" TO "anon";
GRANT ALL ON TABLE "public"."home_fcmtoken" TO "authenticated";
GRANT ALL ON TABLE "public"."home_fcmtoken" TO "service_role";



GRANT ALL ON SEQUENCE "public"."home_fcmtoken_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."home_fcmtoken_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."home_fcmtoken_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."home_featuresuggestion" TO "anon";
GRANT ALL ON TABLE "public"."home_featuresuggestion" TO "authenticated";
GRANT ALL ON TABLE "public"."home_featuresuggestion" TO "service_role";



GRANT ALL ON SEQUENCE "public"."home_featuresuggestion_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."home_featuresuggestion_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."home_featuresuggestion_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."home_feedbacknotification" TO "anon";
GRANT ALL ON TABLE "public"."home_feedbacknotification" TO "authenticated";
GRANT ALL ON TABLE "public"."home_feedbacknotification" TO "service_role";



GRANT ALL ON SEQUENCE "public"."home_feedbacknotification_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."home_feedbacknotification_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."home_feedbacknotification_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."home_giveawayentry" TO "anon";
GRANT ALL ON TABLE "public"."home_giveawayentry" TO "authenticated";
GRANT ALL ON TABLE "public"."home_giveawayentry" TO "service_role";



GRANT ALL ON SEQUENCE "public"."home_giveawayentry_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."home_giveawayentry_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."home_giveawayentry_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."home_giveawaystate" TO "anon";
GRANT ALL ON TABLE "public"."home_giveawaystate" TO "authenticated";
GRANT ALL ON TABLE "public"."home_giveawaystate" TO "service_role";



GRANT ALL ON SEQUENCE "public"."home_giveawaystate_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."home_giveawaystate_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."home_giveawaystate_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."home_giveawaywinner" TO "anon";
GRANT ALL ON TABLE "public"."home_giveawaywinner" TO "authenticated";
GRANT ALL ON TABLE "public"."home_giveawaywinner" TO "service_role";



GRANT ALL ON SEQUENCE "public"."home_giveawaywinner_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."home_giveawaywinner_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."home_giveawaywinner_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."home_matchrequest" TO "anon";
GRANT ALL ON TABLE "public"."home_matchrequest" TO "authenticated";
GRANT ALL ON TABLE "public"."home_matchrequest" TO "service_role";



GRANT ALL ON SEQUENCE "public"."home_matchrequest_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."home_matchrequest_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."home_matchrequest_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."home_message" TO "anon";
GRANT ALL ON TABLE "public"."home_message" TO "authenticated";
GRANT ALL ON TABLE "public"."home_message" TO "service_role";



GRANT ALL ON SEQUENCE "public"."home_message_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."home_message_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."home_message_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."home_option" TO "anon";
GRANT ALL ON TABLE "public"."home_option" TO "authenticated";
GRANT ALL ON TABLE "public"."home_option" TO "service_role";



GRANT ALL ON SEQUENCE "public"."home_option_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."home_option_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."home_option_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."home_profile" TO "anon";
GRANT ALL ON TABLE "public"."home_profile" TO "authenticated";
GRANT ALL ON TABLE "public"."home_profile" TO "service_role";



GRANT ALL ON SEQUENCE "public"."home_profile_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."home_profile_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."home_profile_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."home_profileimage" TO "anon";
GRANT ALL ON TABLE "public"."home_profileimage" TO "authenticated";
GRANT ALL ON TABLE "public"."home_profileimage" TO "service_role";



GRANT ALL ON SEQUENCE "public"."home_profileimage_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."home_profileimage_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."home_profileimage_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."home_question" TO "anon";
GRANT ALL ON TABLE "public"."home_question" TO "authenticated";
GRANT ALL ON TABLE "public"."home_question" TO "service_role";



GRANT ALL ON SEQUENCE "public"."home_question_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."home_question_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."home_question_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."home_roomimage" TO "anon";
GRANT ALL ON TABLE "public"."home_roomimage" TO "authenticated";
GRANT ALL ON TABLE "public"."home_roomimage" TO "service_role";



GRANT ALL ON SEQUENCE "public"."home_roomimage_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."home_roomimage_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."home_roomimage_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."home_roomlisting" TO "anon";
GRANT ALL ON TABLE "public"."home_roomlisting" TO "authenticated";
GRANT ALL ON TABLE "public"."home_roomlisting" TO "service_role";



GRANT ALL ON SEQUENCE "public"."home_roomlisting_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."home_roomlisting_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."home_roomlisting_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."home_roomrequest" TO "anon";
GRANT ALL ON TABLE "public"."home_roomrequest" TO "authenticated";
GRANT ALL ON TABLE "public"."home_roomrequest" TO "service_role";



GRANT ALL ON SEQUENCE "public"."home_roomrequest_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."home_roomrequest_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."home_roomrequest_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."home_savedroomlisting" TO "anon";
GRANT ALL ON TABLE "public"."home_savedroomlisting" TO "authenticated";
GRANT ALL ON TABLE "public"."home_savedroomlisting" TO "service_role";



GRANT ALL ON SEQUENCE "public"."home_savedroomlisting_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."home_savedroomlisting_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."home_savedroomlisting_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."home_spark" TO "anon";
GRANT ALL ON TABLE "public"."home_spark" TO "authenticated";
GRANT ALL ON TABLE "public"."home_spark" TO "service_role";



GRANT ALL ON SEQUENCE "public"."home_spark_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."home_spark_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."home_spark_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."home_sparkstreak" TO "anon";
GRANT ALL ON TABLE "public"."home_sparkstreak" TO "authenticated";
GRANT ALL ON TABLE "public"."home_sparkstreak" TO "service_role";



GRANT ALL ON SEQUENCE "public"."home_sparkstreak_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."home_sparkstreak_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."home_sparkstreak_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."home_staffmember" TO "anon";
GRANT ALL ON TABLE "public"."home_staffmember" TO "authenticated";
GRANT ALL ON TABLE "public"."home_staffmember" TO "service_role";



GRANT ALL ON SEQUENCE "public"."home_staffmember_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."home_staffmember_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."home_staffmember_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."home_supportticket" TO "anon";
GRANT ALL ON TABLE "public"."home_supportticket" TO "authenticated";
GRANT ALL ON TABLE "public"."home_supportticket" TO "service_role";



GRANT ALL ON SEQUENCE "public"."home_supportticket_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."home_supportticket_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."home_supportticket_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."home_ticketmessage" TO "anon";
GRANT ALL ON TABLE "public"."home_ticketmessage" TO "authenticated";
GRANT ALL ON TABLE "public"."home_ticketmessage" TO "service_role";



GRANT ALL ON SEQUENCE "public"."home_ticketmessage_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."home_ticketmessage_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."home_ticketmessage_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."home_useranswer" TO "anon";
GRANT ALL ON TABLE "public"."home_useranswer" TO "authenticated";
GRANT ALL ON TABLE "public"."home_useranswer" TO "service_role";



GRANT ALL ON SEQUENCE "public"."home_useranswer_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."home_useranswer_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."home_useranswer_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."home_userreport" TO "anon";
GRANT ALL ON TABLE "public"."home_userreport" TO "authenticated";
GRANT ALL ON TABLE "public"."home_userreport" TO "service_role";



GRANT ALL ON SEQUENCE "public"."home_userreport_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."home_userreport_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."home_userreport_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."home_voiceparticipant" TO "anon";
GRANT ALL ON TABLE "public"."home_voiceparticipant" TO "authenticated";
GRANT ALL ON TABLE "public"."home_voiceparticipant" TO "service_role";



GRANT ALL ON SEQUENCE "public"."home_voiceparticipant_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."home_voiceparticipant_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."home_voiceparticipant_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."home_voiceroom" TO "anon";
GRANT ALL ON TABLE "public"."home_voiceroom" TO "authenticated";
GRANT ALL ON TABLE "public"."home_voiceroom" TO "service_role";



GRANT ALL ON SEQUENCE "public"."home_voiceroom_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."home_voiceroom_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."home_voiceroom_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."home_wallimage" TO "anon";
GRANT ALL ON TABLE "public"."home_wallimage" TO "authenticated";
GRANT ALL ON TABLE "public"."home_wallimage" TO "service_role";



GRANT ALL ON SEQUENCE "public"."home_wallimage_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."home_wallimage_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."home_wallimage_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."home_wallstroke" TO "anon";
GRANT ALL ON TABLE "public"."home_wallstroke" TO "authenticated";
GRANT ALL ON TABLE "public"."home_wallstroke" TO "service_role";



GRANT ALL ON SEQUENCE "public"."home_wallstroke_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."home_wallstroke_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."home_wallstroke_id_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";































